version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 5
      assignees:
          - "${{ github.repository_owner }}"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
