version: "3.9"
services:
  piwardrive:
    build: .
    ports:
      - "8000:8000"
    command: piwardrive-webui
    volumes:
      - ~/.config/piwardrive:/root/.config/piwardrive
      - ./webui/dist:/app/webui/dist
