[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true
files = [
    "main.py",
    "config.py",
    "diagnostics.py",
    "scheduler.py",
    "utils.py",
    "widgets",
    "tests",
]
exclude = "gitattributes.py"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "screens.*"
ignore_errors = true
follow_imports = "skip"
