[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[project]
name = "piwardrive"
version = "0.1.0"
description = "Headless war-driving toolkit with a Kivy interface"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [{name = "PiWardrive contributors"}]

[project.scripts]
piwardrive = "piwardrive.main:main"
piwardrive-service = "piwardrive.service:main"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true
files = [
    "src/piwardrive/main.py",
    "src/piwardrive/config.py",
    "src/piwardrive/diagnostics.py",
    "src/piwardrive/scheduler.py",
    "src/piwardrive/service.py",
    "src/piwardrive/utils.py",
    "src/piwardrive/widgets",
]
exclude = ".gitattributes"
follow_imports = "skip"

[tool.pydocstyle]
add-ignore = [
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "D200", "D201", "D202", "D203", "D204", "D205", "D206", "D207",
    "D208", "D209", "D210", "D211", "D212", "D213", "D214", "D215",
]

[[tool.mypy.overrides]]
module = "piwardrive.screens.*"
ignore_errors = true
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true
follow_imports = "skip"
