apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: piwardrive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: ssl
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: ssl
          secret:
            secretName: nginx-cert
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: piwardrive
  labels:
    app: nginx

data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        location / {
          proxy_pass http://piwardrive:80;
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-cert
  namespace: piwardrive
stringData:
  cert.pem: |
    dummy
  key.pem: |
    dummy
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: piwardrive
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
