apiVersion: v1
kind: Namespace
metadata:
  name: piwardrive
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: piwardrive
stringData:
  POSTGRES_PASSWORD: changeme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piwardrive
  namespace: piwardrive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piwardrive
  template:
    metadata:
      labels:
        app: piwardrive
    spec:
      containers:
        - name: piwardrive
          image: piwardrive/prod
          env:
            - name: PIWARDRIVE_ENV
              value: "production"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/v1/system/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: piwardrive
  namespace: piwardrive
spec:
  selector:
    app: piwardrive
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: piwardrive
  namespace: piwardrive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: piwardrive
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
