name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install flake8 mypy pytest radon pydocstyle
          pip install -e .
      - name: Lint
        run: flake8 .
      - name: Docstrings
        run: pydocstyle screens widgets
      - name: Type check
        run: mypy
      - name: Complexity check
        run: python scripts/check_complexity.py
      - name: Test
        env:
          KIVY_NO_ARGS: '1'
          KIVY_WINDOW: 'mock'
        run: pytest -q
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build wheel
        run: |
          pip install build
          python -m build
  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tools
        run: |
          pip install buildozer kivy-ios sh pbxproj cookiecutter
      - name: Validate Buildozer config
        run: buildozer --version
      - name: Validate iOS toolchain
        run: toolchain --help
