name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: |
          pip install -r config/requirements.txt
          pip install -r config/requirements-dev.txt
          pip install -e .
          pip install pandas orjson pyprof2calltree

      - name: Build frontend
        working-directory: webui
        run: |
          npm ci
          npm run build

      - name: Run frontend tests
        working-directory: webui
        run: npm run test

      - name: Generate coverage badge
        working-directory: webui
        run: npm run badge

      - name: Commit coverage badge
        uses: EndBug/add-and-commit@v9
        with:
          add: "webui/badges/coverage.svg"
          message: "Update coverage badge"

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml -q

      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: backend
          fail_ci_if_error: true

      - name: Upload Node coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: webui/coverage/lcov.info
          flags: frontend
          fail_ci_if_error: true
