name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
          pip install pandas orjson pyprof2calltree

      - name: Build frontend
        working-directory: webui
        run: |
          npm ci
          npm run build

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
