name: Dependency Updates

on:
    schedule:
        - cron: "0 5 * * 1"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"
            - name: Upgrade packages
              run: |
                  pip install -r config/requirements.txt -r requirements-dev.txt
                  pip list --outdated --format=freeze | cut -d= -f1 | xargs -n1 pip install -U
                  pip freeze > requirements.txt
                  pip freeze > requirements-dev.txt
            - name: Run tests
              run: |
                  pip install -r config/requirements.txt
                  pip install -r config/requirements-dev.txt
                  pytest -q
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "chore: update dependencies"
                  title: "chore: automated dependency update"
                  body: "Automated dependency updates with successful test run."
