name: Build Docs

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Sphinx
        run: pip install sphinx

      - name: Build documentation
        run: SPHINXOPTS="-W" make -C docs html
