name: Node CI

on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webui
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: webui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
