name: Python CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r config/requirements.txt
          pip install -r config/requirements-dev.txt
          pip install -e .
          pip install pandas orjson pyprof2calltree

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=xml -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: backend
          fail_ci_if_error: true
