name: Security Scan

on:
    pull_request:
    schedule:
        - cron: "0 4 * * 1"

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Run bandit
              run: bandit -r src || true
            - name: Run pip-audit
              run: pip-audit -r requirements.txt || true
            - name: Run safety
              run: safety check -r requirements.txt || true
