name: Security Scan

on:
    pull_request:
    schedule:
        - cron: "0 4 * * 1"

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
                  cache: "pip"
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Run bandit
              run: bandit -r src --severity-level medium -f sarif -o bandit.sarif

            - name: Run pip-audit
              run: pip-audit -r requirements.txt -f sarif -o pip_audit.sarif

            - name: Run safety
              run: safety check -r requirements.txt --json > safety.json

            - name: Upload Bandit results
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: bandit.sarif

            - name: Upload pip-audit results
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: pip_audit.sarif

            - name: Upload safety report
              uses: actions/upload-artifact@v4
              with:
                  name: safety-report
                  path: safety.json
